img_size: [120,160]
top_cutoff: 40

# should be an array of 2 elements. The first is the name of the class
# and the second should be the parameters.
# The class should be an abstract instance of LineDetectorInterface
# CUSTOM CONFIG


detector:
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [80,200]
      hough_threshold: 2
      hough_min_line_length: 3
      hough_max_line_gap:    1

      hsv_white1:  [40,0,115]
      hsv_white2:  [175,60,255]
      hsv_yellow1: [20,15,85]
      hsv_yellow2: [50,255,255]
      hsv_red1:    [0,165,120]
      hsv_red2:    [225,255,255]
      hsv_red3:    [165,140,100]
      hsv_red4:    [180,255,255]

detector_intersection:
 - line_detector.LineDetectorHSV
 - configuration:
     dilation_kernel_size: 3
     canny_thresholds: [80,200]
     hough_threshold: 2
     hough_min_line_length: 3
     hough_max_line_gap:    1

      hsv_white1:  [40,0,115]
      hsv_white2:  [175,60,255]
      hsv_yellow1: [20,15,85]
      hsv_yellow2: [50,255,255]
     hsv_red1:    [0,165,120]
     hsv_red2:    [225,255,255]
     hsv_red3:    [165,50,100]
     hsv_red4:    [180,255,255]
